<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks® NonCommercial, Release 5i.4 of 9 de Agosto de 2001 on 27 de Julho de 2005 at 3:33:21 pm</time-stamp>


<class>
<name>Marca2Form</name>
<environment>T2</environment>
<super>GREN.StaticObjectForm</super>
<private>false</private>
<indexed-type>none</indexed-type>
<inst-vars></inst-vars>
<class-inst-vars></class-inst-vars>
<imports></imports>
<category>T2</category>
</class>

<!-- -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -   -->


<methods>
<class-id>T2.Marca2Form class</class-id> <category>classReferences</category>

<body>objectClass    
	    ^T2.Marca2</body>

<body>objectName    
	    ^'Marca2'</body>

<body>pluralObjectName    
	    ^'Marcas2'</body>
</methods>

<methods>
<class-id>T2.Marca2Form class</class-id> <category>interface specs</category>

<body>windowLabel   
	    ^'Marca2'</body>
</methods>

<!-- -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -   -->




</st-source>
