//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:11:33 PM BRT 
//


package captor.domainsystem.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import captor.domainsystem.FormComponentType;
import captor.domainsystem.ParametersType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formComponentType", propOrder = {
    "fullname",
    "parameters"
})
public class FormComponentTypeImpl
    implements FormComponentType
{

    @XmlElement(required = true)
    protected String fullname;
    @XmlElement(type = ParametersTypeImpl.class)
    protected ParametersTypeImpl parameters;

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String value) {
        this.fullname = value;
    }

    public ParametersType getParameters() {
        return parameters;
    }

    public void setParameters(ParametersType value) {
        this.parameters = ((ParametersTypeImpl) value);
    }

}
