//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:11:33 PM BRT 
//


package captor.domainsystem.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import captor.domainsystem.FormComponentsType;
import captor.domainsystem.FormType;
import captor.domainsystem.NextFormsType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formType", propOrder = {
    "id",
    "enabled",
    "name",
    "variant",
    "_extends",
    "nextForms",
    "help",
    "formComponents"
})
public class FormTypeImpl
    implements FormType
{

    @XmlElement(required = true)
    protected String id;
    protected Boolean enabled;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String variant;
    @XmlElement(name = "extends")
    protected String _extends;
    @XmlElement(type = NextFormsTypeImpl.class)
    protected NextFormsTypeImpl nextForms;
    protected String help;
    @XmlElement(type = FormComponentsTypeImpl.class)
    protected FormComponentsTypeImpl formComponents;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String use;
    @XmlAttribute
    protected Boolean isRoot;

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

    public Boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getVariant() {
        return variant;
    }

    public void setVariant(String value) {
        this.variant = value;
    }

    public String getExtends() {
        return _extends;
    }

    public void setExtends(String value) {
        this._extends = value;
    }

    public NextFormsType getNextForms() {
        return nextForms;
    }

    public void setNextForms(NextFormsType value) {
        this.nextForms = ((NextFormsTypeImpl) value);
    }

    public String getHelp() {
        return help;
    }

    public void setHelp(String value) {
        this.help = value;
    }

    public FormComponentsType getFormComponents() {
        return formComponents;
    }

    public void setFormComponents(FormComponentsType value) {
        this.formComponents = ((FormComponentsTypeImpl) value);
    }

    public String getUse() {
        return use;
    }

    public void setUse(String value) {
        this.use = value;
    }

    public Boolean isIsRoot() {
        return isRoot;
    }

    public void setIsRoot(Boolean value) {
        this.isRoot = value;
    }

}
