//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:11:33 PM BRT 
//


package captor.domainsystem.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import captor.domainsystem.FormType;
import captor.domainsystem.FormsType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formsType", propOrder = {
    "name",
    "form"
})
public class FormsTypeImpl
    implements FormsType
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true, type = FormTypeImpl.class)
    protected List<FormType> form;

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public List<FormType> getForm() {
        if (form == null) {
            form = new ArrayList<FormType>();
        }
        return this.form;
    }

}
