//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:11:33 PM BRT 
//


package captor.domainsystem.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import captor.domainsystem.NextFormType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nextFormType", propOrder = {
    "id",
    "minChilds",
    "maxChilds"
})
public class NextFormTypeImpl
    implements NextFormType
{

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String minChilds;
    @XmlElement(required = true)
    protected String maxChilds;

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

    public String getMinChilds() {
        return minChilds;
    }

    public void setMinChilds(String value) {
        this.minChilds = value;
    }

    public String getMaxChilds() {
        return maxChilds;
    }

    public void setMaxChilds(String value) {
        this.maxChilds = value;
    }

}
