//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:11:33 PM BRT 
//


package captor.domainsystem.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import captor.domainsystem.FormComponentType;
import captor.domainsystem.FormComponentsType;
import captor.domainsystem.FormType;
import captor.domainsystem.FormsType;
import captor.domainsystem.NextFormType;
import captor.domainsystem.NextFormsType;
import captor.domainsystem.OrType;
import captor.domainsystem.ParameterType;
import captor.domainsystem.ParametersType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the captor.domainsystem.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Forms_QNAME = new QName("", "forms");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: captor.domainsystem.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FormComponentsType }
     * 
     */
    public FormComponentsTypeImpl createFormComponentsType() {
        return new FormComponentsTypeImpl();
    }

    /**
     * Create an instance of {@link NextFormsType }
     * 
     */
    public NextFormsTypeImpl createNextFormsType() {
        return new NextFormsTypeImpl();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterTypeImpl createParameterType() {
        return new ParameterTypeImpl();
    }

    /**
     * Create an instance of {@link FormType }
     * 
     */
    public FormTypeImpl createFormType() {
        return new FormTypeImpl();
    }

    /**
     * Create an instance of {@link FormComponentType }
     * 
     */
    public FormComponentTypeImpl createFormComponentType() {
        return new FormComponentTypeImpl();
    }

    /**
     * Create an instance of {@link NextFormType }
     * 
     */
    public NextFormTypeImpl createNextFormType() {
        return new NextFormTypeImpl();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersTypeImpl createParametersType() {
        return new ParametersTypeImpl();
    }

    /**
     * Create an instance of {@link FormsType }
     * 
     */
    public FormsTypeImpl createFormsType() {
        return new FormsTypeImpl();
    }

    /**
     * Create an instance of {@link OrType }
     * 
     */
    public OrTypeImpl createOrType() {
        return new OrTypeImpl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormsTypeImpl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "forms")
    public JAXBElement<FormsTypeImpl> createForms(FormsTypeImpl value) {
        return new JAXBElement<FormsTypeImpl>(_Forms_QNAME, FormsTypeImpl.class, null, value);
    }

}
