//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.22 at 02:36:31 GMT-03:00 
//


package captor.domainsystem;


/**
 * Java content class for formType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Dev/Captor/dev/scripts/jaxb/DOMAIN.XSD line 21)
 * <p>
 * <pre>
 * &lt;complexType name="formType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([a-zA-ZçÇãÃáéíóúÁÉÍÓÚâêîôûÂÊÎÔÛUüÜ*\.\s\-_0-9])+"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="name">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([a-zA-ZçÇãÃáéíóúÁÉÍÓÚâêîôûÂÊÎÔÛUüÜ\.\s\-_0-9])+"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="variant">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([a-zA-ZçÇãÃáéíóúÁÉÍÓÚâêîôûÂÊÎÔÛUüÜ\.\s\-_0-9])+"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="extends" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nextForms" type="{}nextFormsType" minOccurs="0"/>
 *         &lt;element name="help" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formComponents" type="{}formComponentsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isRoot" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="use" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FormType {


    /**
     * Gets the value of the variant property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getVariant();

    /**
     * Sets the value of the variant property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setVariant(java.lang.String value);

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getHelp();

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setHelp(java.lang.String value);

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExtends();

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExtends(java.lang.String value);

    /**
     * Gets the value of the enabled property.
     * 
     */
    boolean isEnabled();

    /**
     * Sets the value of the enabled property.
     * 
     */
    void setEnabled(boolean value);

    /**
     * Gets the value of the formComponents property.
     * 
     * @return
     *     possible object is
     *     {@link captor.domainsystem.FormComponentsType}
     */
    captor.domainsystem.FormComponentsType getFormComponents();

    /**
     * Sets the value of the formComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link captor.domainsystem.FormComponentsType}
     */
    void setFormComponents(captor.domainsystem.FormComponentsType value);

    /**
     * Gets the value of the isRoot property.
     * 
     */
    boolean isIsRoot();

    /**
     * Sets the value of the isRoot property.
     * 
     */
    void setIsRoot(boolean value);

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

    /**
     * Gets the value of the nextForms property.
     * 
     * @return
     *     possible object is
     *     {@link captor.domainsystem.NextFormsType}
     */
    captor.domainsystem.NextFormsType getNextForms();

    /**
     * Sets the value of the nextForms property.
     * 
     * @param value
     *     allowed object is
     *     {@link captor.domainsystem.NextFormsType}
     */
    void setNextForms(captor.domainsystem.NextFormsType value);

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUse();

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUse(java.lang.String value);

}
