//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.22 at 02:36:31 GMT-03:00 
//


package captor.domainsystem;


/**
 * Java content class for formComponentType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Dev/Captor/dev/scripts/jaxb/DOMAIN.XSD line 87)
 * <p>
 * <pre>
 * &lt;complexType name="formComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fullname">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([a-zA-Z\.\s\-_0-9])+"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="parameters" type="{}parametersType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FormComponentType {


    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link captor.domainsystem.ParametersType}
     */
    captor.domainsystem.ParametersType getParameters();

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link captor.domainsystem.ParametersType}
     */
    void setParameters(captor.domainsystem.ParametersType value);

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFullname();

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFullname(java.lang.String value);

}
